### ISSUE TITLE
Deleted files are still attempting upload

### ISSUE THREAD

**Issue by mneil** [HeliosInteractive/swag-sync#11]
Transfering files over winscp creates a filepart file that is cached and repeatedly tries to upload. It fails with the following error.

```
swag-sync.exe Error: 0 : Uploading The file indicated by the FilePath property does not exist! failed due to exception: /home/helios/reach/storage/swag3/reach-wax.png.filepart
    ProcessId=2011
    ThreadId=1
    DateTime=2016-04-15T23:58:14.4542040Z
```

If I upload a file then remove it, and the file never finished, then it will also do the same thing.

**Comment by 3p3r** [comment]
"Partially" fixed by 80d482432fcb580980a01554c127b8d8bef67e8b
Deleted files, remained from old database queries now exceed failed retry attempts.
