### ISSUE TITLE
Do not count tcp errors/exceptions as failed attempts

### ISSUE THREAD

**Issue by mneil** [HeliosInteractive/swag-sync#16]
ECONNRESET
ECONNABORTED
ECONNREFUSED
ETIMEDOUT
HOST_NOT_FOUND

The hardest list in the world to find https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668(v=vs.85).aspx

**Comment by 3p3r** [comment]
Fixed per a5d4b8c32775a5dc3f26df8e21d214bbd06a7347
