### ISSUE TITLE
Turn down logging

### ISSUE THREAD

**Issue by mneil** [HeliosInteractive/swag-sync#27]
I'm getting logs like the following which I feel are too verbose.

```
swag-sync.exe Information: 0 :

Max count exceeded. Ignoring /home/helios/reach/storage/reachdata/swagsync/test/c157e619-6a95-4ba8-93e1-d1595f2f01b4.jpg

swag-sync.exe Information: 0 : Checking for Internet connectivity...

swag-sync.exe Information: 0 : Internet connectivity check passed.

swag-sync.exe Information: 0 : Cleaning database...
```

The stuff I care about are:
- startup
- start uploading
- finished/failed upload
- the buckets I'm watching
- Internet not available
- Internet connection restored (I don't need to know when you're checking)

**Comment by 3p3r** [comment]
Fixed by cbb6b3ea5f390206834072494abaebfd5fcafe0c
You can pass log verbosity in command line now.
